from app.error_codes import *

ERROR_CODE_MAP = {
    400: VALIDATION_ERROR,
    401: AUTH_INVALID_TOKEN,
    403: RBAC_FORBIDDEN,
    422: VALIDATION_ERROR,
    429: RATE_LIMITED,
    500: INTERNAL_ERROR,
    503: DB_UNAVAILABLE,
}