# 🔐 Auth
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
AUTH_EXPIRED_TOKEN = "AUTH_EXPIRED_TOKEN"

# 🔒 Authorization / Security
RBAC_FORBIDDEN = "RBAC_FORBIDDEN"
PII_FORBIDDEN = "PII_FORBIDDEN"

# 📥 Validation
VALIDATION_ERROR = "VALIDATION_ERROR"

# 🚦 Rate limiting
RATE_LIMITED = "RATE_LIMITED"

# 🗄️ Database
DB_TIMEOUT = "DB_TIMEOUT"
DB_UNAVAILABLE = "DB_UNAVAILABLE"

# ⚠️ System
INTERNAL_ERROR = "INTERNAL_ERROR"